# Generated by Django 5.1.2 on 2024-12-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='plano',
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formadepagamento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plano'),
        ),
    ]
